### ISSUE TITLE
Update Readme About Browser Support

### ISSUE THREAD

**Issue by Cleod9** [zzarcon/growy#1]
Before I say anything I just want to note that this is a very clean and solid example of how a web component should look, nice work! 😄

Anyways, I got this error in Firefox 48.0.1:

```
TypeError: document.registerElement is not a function
```

Since Web Components are still in Draft in the HTML spec, I recommend documenting how to run this in non-Chrome browsers (i.e. Firefox doesn't have custom elements enabled by default)

**Comment by zzarcon** [comment]
Hi @Cleod9 really good point, I just added it to the Readme, let me know if it's clear now for you https://github.com/zzarcon/growy/commit/11d3218f7a35e4477b42e047f8cf57332015987d

Anyways, feedback is welcome, so feel free to add/fix whatever you think can be done.

Thanks!

**Comment by Cleod9** [comment]
Cool, that reads well to me. Thanks!
